apiVersion: v1
kind: ConfigMap
metadata:
  name: env-guetta-api
data:
  TOKEN: <YOUR-TOKEN>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guetta-api
spec:
  selector:
    matchLabels:
      app: guetta-api
  template:
    metadata:
      labels:
        app: guetta-api
    spec:
      containers:
      - name: guetta
        image: redbaty/guetta-api:latest
        envFrom:
          - configMapRef:
              name: env-guetta-api
        startupProbe:
          httpGet:
            path: /health/startup
            port: 80
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3        
        resources:
          limits:
            memory: "512Mi"
            cpu: "4"
        ports:
        - containerPort: 80